### ISSUE TITLE
Убрать модуль uuid из зависимостей

### ISSUE THREAD

**Issue by a1tus** [yoomoney/yandex-checkout-sdk-python#63]
Добрый день.

На данный момент в requirements.txt и setup.py как зависимость указан модуль uuid (https://pypi.org/project/uuid/).
Но он не нужен для поддерживаемых версий питона 2.7, 3+, т.к. он в них есть по умолчанию (есть даже в 2.6).

Из-за этого при установке yandex_cheсkout просто устанавливается лишний пакет, но даже не используется (т.к. при импорте питон берет свой). Более того, если этот пакет установлен, это даже может приводить к проблемам с остановкой других модулей, т.к. он несовместим с py3.

Предлагаю убрать эту зависимость.

**Comment by ostulov** [comment]
Добрый день!

Благодарю за обращение, рассмотрим Ваше предложение!

**Comment by ipeterov** [comment]
FYI у меня не получалось установить пакет из-за syntax error в пакете uuid (почему то там использовался python2 only код). Пришлось ставить https://pypi.org/project/yandex-checkout-no-uuid/

**Comment by ostulov** [comment]
Добрый день!

Для удаления зависимости нам необходимо проверить, как это скажется на более ранних версиях Питона. После исследования мы сможем принять решение, будем удалять зависимость ли нет.

**Comment by a1tus** [comment]
Если это успростит дело, то сразу могу сказать, что это скажется только на людях с python < 2.5.
То есть в 2.5 этот модуль как раз и был добавлен (2006 год).

Думаю, можно смело предположить, что люди с таким питоном не будут обновлять или устанавливать последнюю версию данной библиотеки.

При этом проблемы с текущими версиями вполне реальны.

**Comment by barbashov** [comment]
Добрый день. Нам тоже билд это ломает билд проекта.
Уберите пожалуйста. Серьезно, uuid в питоне уже миллион лет.

**Comment by ostulov** [comment]
Добрый день!

Вышел новый репозиторий https://github.com/yoomoney/yookassa-sdk-python, в котором теперь будут выходить обновления пакета.
Зависимость от uuid в новом пакете убрана.
