### ISSUE TITLE
yookassa migration

### ISSUE THREAD

**Issue by bird-in-hat** [yoomoney/yandex-checkout-sdk-python#66]
Пришло письмо от Яндекс кассы. Используем SDK 1.6.3

> Здравствуйте.
> 
> После ребрендинга мы внесли изменения в платёжные протоколы и реестры. Пожалуйста, посмотрите список изменений и обновите настройки на своей стороне, если нужно. 
> 
> — Если подключены по платёжному API (или используете платёжный виджет)
> 
> Обновите ссылки и параметры (обновлять их нужно одновременно):
> 
>     Новый URL для запросов: https://api.yookassa.ru/v3
>     Новый код способа оплаты: yoo_money (вместо «yandex_money») — передавайте нам yoo_money в качестве способа оплаты. Также он используется во входящих уведомлениях и в информации о платеже.
>     Обновление в объекте cancellation_details: если ЮKassa отменила платёж или платёж прошел с ошибкой, будем отдавать "party" : " yoo_kassa" (вместо "party" : "yandex_checkout"). 

Нужно ли будет менять `yandex_checkout.configuration.Configuration.api_url` с "https://payment.yandex.net/api/v3" на "https://api.yookassa.ru/v3"?

**Comment by ostulov** [comment]
Добрый день!

Мы уже ведем работу над подготовкой обновления для SDK в связи с изменениями адресов. Обновление выйдет на этой неделе. Все необходимые изменения адресов в обновлении будут учтены.

**Comment by ostulov** [comment]
Добрый день!

Для переезда подготовлен новый репозиторий - https://github.com/yoomoney/yookassa-sdk-python
Вам необходимо перейти на его использование.

**Comment by bird-in-hat** [comment]
Спасибо!
