### ISSUE TITLE
yookassa migration yandex-checkout-sdk-python

### ISSUE THREAD

**Issue by Burovytskyi** [yoomoney/yandex-checkout-sdk-python#67]
Добрый день. Получил письмо от Яндекса, про смену урлов.
Использую библиотеку [yandex-checkout-sdk-python](https://github.com/yoomoney/yandex-checkout-sdk-python), она уже изменена под нововведения yookassa? 
Если нет, то будет ли исправлена под новые урлы и когда?

**Comment by ostulov** [comment]
Добрый день!

Для переезда подготовлен новый репозиторий - https://github.com/yoomoney/yookassa-sdk-python
Вам необходимо перейти на его использование.

**Comment by Burovytskyi** [comment]
> Добрый день!
> 
> Для переезда подготовлен новый репозиторий - https://github.com/yoomoney/yookassa-sdk-python
> Вам необходимо перейти на его использование.

Спасибо!
